base_url = "https://engineering-playbook.upte.ch"
compile_sass = true
title = "UpTech Works, LLC - Engineering Playbook"
build_search_index = true

theme = "zola_docsascode_theme"
taxonomies = [
    {name = "tags", rss = true},
    {name = "authors", rss = true},
]

# theme = "adidoks"

# theme = "book"

# theme = "zola_easydocs_theme"

[markdown]
highlight_code = true
highlight_theme = "kronuz"

[extra]
